### ISSUE TITLE
"New" button stays focused after clicking

### ISSUE THREAD

**Issue by mrichards42** [mrichards42/sedecordle-bot#1]
> On desktop if I click new, then type a word and hit enter, it makes a new game

I ran into focus issues, but apparently I only fixed it for the hints button: https://github.com/mrichards42/sedecordle-bot/blob/9d06ac24c834bfbff0edfeb93f741de33e0de7dd/src/components/GameContainer.tsx#L22-L25

Probably should just handle this in [TextButton](https://github.com/mrichards42/sedecordle-bot/blob/9d06ac24c834bfbff0edfeb93f741de33e0de7dd/src/components/Button.tsx#L3-L9) itself.

@devinhammond plz fix :)

**Comment by devinhammond** [comment]
Pull request submitted, fixing the "New" button in-line. A global solution would require more thoughtful exploration of button behavior, and most likely YAGNI. Maybe some buttons want to stay focused?
